apiVersion: v1
kind: Service
metadata:
  name: optimizer-api
  namespace: cost-optimizer
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
    - name: metrics
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app.kubernetes.io/component: api
