# Chart Testing Configuration

remote: origin
target-branch: main
chart-dirs:
  - infrastructure/helm
chart-repos:
  - bitnami=https://charts.bitnami.com/bitnami
helm-extra-args: --timeout 600s
check-version-increment: false
debug: true
