apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-cost-optimizer
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: cost-optimizer

  # Source using Kustomize
  source:
    repoURL: https://github.com/your-org/k8s-cost-optimizer.git
    targetRevision: HEAD
    path: infrastructure/kustomize/overlays/dev

  # Destination
  destination:
    server: https://kubernetes.default.svc
    namespace: cost-optimizer-dev

  # Sync policy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  # Health assessment
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
